### ISSUE TITLE
UI: Encode prediction parameters in the URL

### ISSUE THREAD

**Issue by danielrichman** [cuspaceflight/tawhiri#103]
The main requirement is for people to be able to share predictions with each other by copying a URL.

The solution we've been planning is
- Prediction parameters encoded into URLs with HTML5 history storing and loading
- No persistent state on the server. If it becomes necessary, a caching layer in front of the API can avoid re-runs of a popular prediction.
- Wishlist/maybe: shortlink server to produce small ids for sharing

**Comment by adamgreig** [comment]
Closed while we rethink the UI.
