### ISSUE TITLE
Issue warnings when altitude goes out of range

### ISSUE THREAD

**Issue by danielrichman** [cuspaceflight/tawhiri#26]
Currently we allow the lerp constant for altitude to go out of `[0, 1]` since we want to extrapolate at the top and bottom (balloons sometimes go slightly over the top @ 40k, and the bottom alt level can often be a few hundred m ASL).

A lerp constant out of this range is (exactly) linear extrapolation.

We should cap this (at say, an absolute value of metres, or perhaps via demanding the lerp constant stays in range `[-1, 2]`).

**Comment by adamgreig** [comment]
We now do this, via the warnings.pyx module.
