### ISSUE TITLE
Varying more parameters

### ISSUE THREAD

**Issue by danielrichman** [cuspaceflight/tawhiri#81]
So, currently we can vary time via the "hourly" box.

It'd be nice to be able to vary ascent/descent and burst, since those are high variance (what with it being quite difficult to fill a balloon accurately).

I had a few ideas:
- Allowing the inputs to take either a single integer "N" or something like "start..stop" or "start..stride..stop" or "start..stop;N" (where N would behave like the num arg to `linspace`)
  This doesn't work very well for launch time, since that input would be very long. Perhaps we could handle this separately.
- Cap the number of predictions we run. I think that too many would overload the client; the server probably doesn't care?
  - sub idea: if (product of options) > N, then sample from the ranges randomly.
  - or maybe if > N, switch to dots only (no lines); if > M then sample randomly?
- Is it worth varying launch location? I don't think so, personally.

Any thoughts or votes?

**Comment by adamgreig** [comment]
Closed while we rethink the UI.
