### ISSUE TITLE
UI Refactoring

### ISSUE THREAD

**Issue by danielrichman** [cuspaceflight/tawhiri#82]
I propose:
- break cusf_tawhiri_ui.js up into a few files
  - ui: Map, Form, SlidingPanel, ...
  - predictions: Path, Request, Prediction, ...
- remove the "Request" class and just make it a single function (the request class now only has a single method, 'submit', since moving over to the new API simplified things a lot :-) )
- rename "Path" -> "Prediction" and "Prediction" -> "PredictionCollection" (or some similar name) to better match how things are named server-side/in the api

@mattjudge any thoughts / are you happy for me to go ahead and do this?

**Comment by adamgreig** [comment]
Closed while we rethink the UI.
